[package]
name = "carcinisation"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
members = [
    "scripts/generate-palettes",
    "scripts/generate-typeface",
    "scripts/process-gfx",
    "scripts/validate-data",
]

[dependencies]
bevy = "0.11.0" #dynamic_linking cannot be used for webassembly, not required for MacOS
#bevy = { version = "0.11.0", features = ["dynamic_linking"] } #requred for Windows builds
bevy_common_assets = { version = "0.7.0", default-features = true, features = [
    "toml",
    "ron",
    "yaml",
    "json",
] }
bevy_framepace = "0.13.3"
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls" }
leafwing-input-manager = "0.10.0"
rand = "0.8.4"
seldom_pixel = { git = "https://github.com/Seldom-SE/seldom_pixel", default-features = true, features = [
    "line",
] }
serde = "1.0.183"
serde_derive = "1.0.183"
toml = "0.8.0"
wasm-bindgen = "0.2.74"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }