[package]
name = "carcinisation"
version = "0.2.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
opt-level = 'z'

[workspace]
resolver = "2"
members = [
    "assert_assets_path",
    "scripts/generate-palettes",
    "scripts/generate-typeface",
    "scripts/process-gfx",
]

[dependencies]
assert_assets_path = { path = "assert_assets_path" }
bevy = { version = "0.12", features = [
    "wayland",
] } # dynamic_linking cannot be used for webassembly, not required for MacOS
# bevy = { version = "0.12", features = ["dynamic_linking"] } # required for Windows builds
bevy_editor_pls = "0.6.0"
bevy_framepace = "0.14.1"
lazy_static = "1.4.0"
leafwing-input-manager = "0.11.2"
num_enum = "0.7.1"
rand = "0.8.5"
seldom_fn_plugin = "0.5.0"
seldom_pixel = { path = "/Users/marcotoniut/repos/seldom_pixel", default-features = true, features = [
    "line",
] }
strum = "0.25.0"
strum_macros = "0.25.0"
wasm-bindgen = "0.2.87"
