[package]
name = "my_bevy_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# bevy = "0.11.0"
bevy = { git = "https://github.com/Selene-Amanita/bevy.git", branch = "allow-unfocused-window-creation" }
rand = "0.8.4"
cocoa = "0.25.0"
objc = "0.2.6"
