[package]
name = "punished-gb"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
members = [
    "scripts/generate-palettes",
    "scripts/generate-typeface",
    "scripts/process-gfx",
]

[dependencies]
bevy = "0.11.0"
#bevy = { version = "0.11.0", features = ["dynamic_linking"] }
bevy_framepace = "0.13.3"
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls" }
#cocoa = "0.25.0"
leafwing-input-manager = "0.10.0"
#objc = "0.2.6"
rand = "0.8.4"
seldom_pixel = { git = "https://github.com/Seldom-SE/seldom_pixel", default-features = true, features = [
    "line",
] }
