[package]
name = "carcinisation"
version = "0.2.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
opt-level = 'z'

[workspace]
resolver = "2"
members = [
    "assert_assets_path",
    "scripts/generate-palettes",
    "scripts/generate-typeface",
    "scripts/process-gfx",
]

[dependencies]
assert_assets_path = { path = "assert_assets_path" }
bevy = { version = "0.11.3", features = [
    "wayland",
] } # dynamic_linking cannot be used for webassembly, not required for MacOS
#bevy = { version = "0.11.3", features = ["dynamic_linking"] } #requred for Windows builds
bevy_framepace = "0.13.3"
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls" }
lazy_static = "1.4.0"
leafwing-input-manager = "0.10.0"
num_enum = "0.7.1"
rand = "0.8.5"
seldom_pixel = { git = "https://github.com/marcotoniut/seldom_pixel", default-features = true, features = [
    "line",
] }
strum = "0.25.0"
strum_macros = "0.25.0"
wasm-bindgen = "0.2.87"
