[package]
name = "punished-gb"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["scripts/quantize-sprites"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
cocoa = "0.25.0"
objc = "0.2.6"
rand = "0.8.4"
seldom_pixel = { git = "https://github.com/Seldom-SE/seldom_pixel" }

[package.scripts]
dev = "cargo watch -x 'run --features bevy/dynamic_linking'"
quantize-sprites = "cd scripts/quantize-sprites; cargo run"
