[[images]]
name = "enemy"
path = "sprites/ball_red_large.png"
invert_colors = true
width = 12

[[images]]
name = "star"
path = "sprites/star.png"
width = 8

[[images]]
name = "score-icon"
target_path = "sprites/score-icon.png"
invert_colors = true
path = "sprites/star.png"
width = 10


[[images]]
name = "enemy-icon"
target_path = "sprites/enemy-count-icon.png"
invert_colors = true
path = "sprites/ball_red_large.png"
width = 10

[[images]]
path = "sprites/melee_slash.png"

[[images]]
path = "sprites/bullet_particles.png"

[[images]]
path = "sprites/crosshairs/squiggly.png"

[[images]]
path = "sprites/crosshairs/gun_sight.png"

[[images]]
path = "sprites/crosshairs/gun_sight.png"
target_path = "sprites/crosshairs/gun_sight_inverted.png"
invert_colors = true

[[images]]
path = "backgrounds/asteroid/background.png"
[[images]]
path = "backgrounds/asteroid/skybox.png"
[[images]]
path = "backgrounds/asteroid/spaceship_destroyed.png"

[[images]]
path = "backgrounds/rugpark/background.png"
[[images]]
path = "backgrounds/rugpark/skybox.png"

[[images]]
path = "backgrounds/spaceship/background.png"
[[images]]
path = "backgrounds/spaceship/skybox.png"

[[images]]
path = "main_menu/blank.png"

[[images]]
path = "typeface/typeface.png"

[[images]]
name = "pixeboy"
path = "typeface/pixeboy.png"

[[images]]
path = "typeface/pixeboy.png"
target_path = "typeface/pixeboy-inverted.png"
invert_colors = true

[[images]]
path = "typeface/animated_typeface.png"

# Enemies
width = 2
[[images]]
path = "sprites/enemies/mosquito_death_6.png"
target_path = "sprites/enemies/mosquito_death_8.png"
width = 6
[[images]]
path = "sprites/enemies/mosquito_death_6.png"
target_path = "sprites/enemies/mosquito_death_7.png"
width = 10
[[images]]
path = "sprites/enemies/mosquito_death_6.png"
[[images]]
path = "sprites/enemies/mosquito_death_5.png"
[[images]]
path = "sprites/enemies/mosquito_death_4.png"
[[images]]
path = "sprites/enemies/mosquito_death_4.png"
target_path = "sprites/enemies/mosquito_death_3.png"
width = 50

[[images]]
path = "sprites/enemies/mosquito_fly_6.png"
target_path = "sprites/enemies/mosquito_fly_8.png"
width = 6
[[images]]
path = "sprites/enemies/mosquito_fly_6.png"
target_path = "sprites/enemies/mosquito_fly_7.png"
width = 10
[[images]]
path = "sprites/enemies/mosquito_fly_6.png"
[[images]]
path = "sprites/enemies/mosquito_fly_5.png"
[[images]]
path = "sprites/enemies/mosquito_fly_4.png"
[[images]]
path = "sprites/enemies/mosquito_fly_4.png"
target_path = "sprites/enemies/mosquito_fly_3.png"
width = 50

[[images]]
path = "sprites/enemies/mosquito_idle_6.png"
target_path = "sprites/enemies/mosquito_idle_8.png"
width = 6
[[images]]
path = "sprites/enemies/mosquito_idle_6.png"
target_path = "sprites/enemies/mosquito_idle_7.png"
width = 10
[[images]]
path = "sprites/enemies/mosquito_idle_6.png"
[[images]]
path = "sprites/enemies/mosquito_idle_5.png"
[[images]]
path = "sprites/enemies/mosquito_idle_4.png"
[[images]]
path = "sprites/enemies/mosquito_idle_4.png"
target_path = "sprites/enemies/mosquito_idle_3.png"
width = 50

# TODO Is this necessary?
[[images]]
path = "sprites/enemies/mosquito_melee_6.png"
target_path = "sprites/enemies/mosquito_melee_8.png"
width = 6
[[images]]
path = "sprites/enemies/mosquito_melee_6.png"
target_path = "sprites/enemies/mosquito_melee_7.png"
width = 10
[[images]]
path = "sprites/enemies/mosquito_melee_6.png"
[[images]]
path = "sprites/enemies/mosquito_melee_5.png"
[[images]]
path = "sprites/enemies/mosquito_melee_4.png"
[[images]]
path = "sprites/enemies/mosquito_melee_4.png"
target_path = "sprites/enemies/mosquito_melee_3.png"
width = 50

# [[images]]
# path = "sprites/enemies/mosquito_hydra_idle.png"
# [[images]]
# path = "sprites/enemies/mosquito_hydra_shooting.png"
# [[images]]
# path = "sprites/enemies/mosquito_head_shot.png"

[[images]]
path = "sprites/enemies/spider_idle_7.png"
[[images]]
path = "sprites/enemies/spider_death_7.png"
[[images]]
path = "sprites/enemies/spider_boss_attack.png"
[[images]]
path = "sprites/enemies/spider_boss_death.png"
[[images]]
path = "sprites/enemies/spider_boss.png"
[[images]]
path = "sprites/enemies/spider_boss_web.png"
[[images]]
path = "sprites/enemies/spider_boss_web_attack.png"
[[images]]
path = "sprites/enemies/worm.png"
[[images]]
path = "sprites/enemies/worm_death.png"

[[images]]
path = "sprites/enemies/tardigrade_death_64x64.png"
target_path = "sprites/enemies/tardigrade_death_8.png"
width = 24
[[images]]
path = "sprites/enemies/tardigrade_death_64x64.png"
target_path = "sprites/enemies/tardigrade_death_7.png"
width = 42
[[images]]
path = "sprites/enemies/tardigrade_death_64x64.png"
target_path = "sprites/enemies/tardigrade_death_6.png"

[[images]]
path = "sprites/enemies/tardigrade_idle_64x64.png"
target_path = "sprites/enemies/tardigrade_idle_8.png"
width = 24
[[images]]
path = "sprites/enemies/tardigrade_idle_64x64.png"
target_path = "sprites/enemies/tardigrade_idle_7.png"
width = 42
[[images]]
path = "sprites/enemies/tardigrade_idle_64x64.png"
target_path = "sprites/enemies/tardigrade_idle_6.png"

[[images]]
path = "sprites/enemies/tardigrade_attack_64x64.png"
target_path = "sprites/enemies/tardigrade_attack_8.png"
width = 24
[[images]]
path = "sprites/enemies/tardigrade_attack_64x64.png"
target_path = "sprites/enemies/tardigrade_attack_7.png"
width = 42
[[images]]
path = "sprites/enemies/tardigrade_attack_64x64.png"
target_path = "sprites/enemies/tardigrade_attack_6.png"

[[images]]
path = "sprites/enemies/tardigrade_sucking_64x64.png"
target_path = "sprites/enemies/tardigrade_sucking_8.png"
width = 24
[[images]]
path = "sprites/enemies/tardigrade_sucking_64x64.png"
target_path = "sprites/enemies/tardigrade_sucking_7.png"
width = 42
[[images]]
path = "sprites/enemies/tardigrade_sucking_64x64.png"
target_path = "sprites/enemies/tardigrade_sucking_6.png"

# Objects
[[images]]
path = "sprites/objects/bench_big.png"
[[images]]
path = "sprites/objects/bench_small.png"
[[images]]
path = "sprites/objects/fiber_tree.png"
[[images]]
path = "sprites/objects/rugpark_sign.png"

# Destructibles
[[images]]
path = "sprites/objects/lamp_broken_3.png"
[[images]]
path = "sprites/objects/lamp_base_3.png"
[[images]]
path = "sprites/objects/trashcan_base_6.png"
[[images]]
path = "sprites/objects/trashcan_base_4.png"
[[images]]
path = "sprites/objects/trashcan_broken_6.png"
[[images]]
path = "sprites/objects/trashcan_broken_4.png"
[[images]]
path = "sprites/objects/crystal_base_5.png"
[[images]]
path = "sprites/objects/crystal_broken_5.png"
[[images]]
path = "sprites/objects/mushroom_base_4.png"
[[images]]
path = "sprites/objects/mushroom_broken_4.png"

# Pickups
[[images]]
path = "sprites/pickups/ammo_9x8.png"
target_path = "sprites/pickups/ammo_6.png"
[[images]]
path = "sprites/pickups/ammo_13x12.png"
target_path = "sprites/pickups/ammo_4.png"
[[images]]
path = "sprites/pickups/bomb_9x9.png"
target_path = "sprites/pickups/bomb_6.png"
[[images]]
path = "sprites/pickups/bomb_13x11.png"
target_path = "sprites/pickups/bomb_4.png"
[[images]]
path = "sprites/pickups/health_9x7.png"
target_path = "sprites/pickups/health_6.png"
[[images]]
path = "sprites/pickups/health_14x10.png"
target_path = "sprites/pickups/health_4.png"

# Attacks
[[images]]
path = "sprites/attacks/bloodball_45x45.png"
target_path = "sprites/attacks/blood_attack_hovering_8.png"
width = 2
[[images]]
path = "sprites/attacks/bloodball_45x45.png"
target_path = "sprites/attacks/blood_attack_hovering_7.png"
width = 4
[[images]]
path = "sprites/attacks/bloodball_45x45.png"
target_path = "sprites/attacks/blood_attack_hovering_6.png"
width = 6
[[images]]
path = "sprites/attacks/bloodball_45x45.png"
target_path = "sprites/attacks/blood_attack_hovering_5.png"
width = 10
[[images]]
path = "sprites/attacks/bloodball_45x45.png"
target_path = "sprites/attacks/blood_attack_hovering_4.png"
width = 15
[[images]]
path = "sprites/attacks/bloodball_45x45.png"
target_path = "sprites/attacks/blood_attack_hovering_3.png"
width = 21
[[images]]
path = "sprites/attacks/bloodball_45x45.png"
target_path = "sprites/attacks/blood_attack_hovering_2.png"
width = 28
[[images]]
path = "sprites/attacks/bloodball_45x45.png"
target_path = "sprites/attacks/blood_attack_hovering_1.png"
width = 36
[[images]]
path = "sprites/attacks/bloodsplat.png"
target_path = "sprites/attacks/blood_attack_hit_0.png"

[[images]]
path = "sprites/attacks/boulder_56x56.png"
target_path = "sprites/attacks/boulder_attack_hovering_8.png"
width = 2
[[images]]
path = "sprites/attacks/boulder_56x56.png"
target_path = "sprites/attacks/boulder_attack_hovering_7.png"
width = 5
[[images]]
path = "sprites/attacks/boulder_56x56.png"
target_path = "sprites/attacks/boulder_attack_hovering_6.png"
width = 9
[[images]]
path = "sprites/attacks/boulder_56x56.png"
target_path = "sprites/attacks/boulder_attack_hovering_5.png"
width = 14
[[images]]
path = "sprites/attacks/boulder_56x56.png"
target_path = "sprites/attacks/boulder_attack_hovering_4.png"
width = 20
[[images]]
path = "sprites/attacks/boulder_56x56.png"
target_path = "sprites/attacks/boulder_attack_hovering_3.png"
width = 28
[[images]]
path = "sprites/attacks/boulder_56x56.png"
target_path = "sprites/attacks/boulder_attack_hovering_2.png"
width = 36
[[images]]
path = "sprites/attacks/boulder_56x56.png"
target_path = "sprites/attacks/boulder_attack_hovering_1.png"
width = 46
[[images]]
path = "sprites/attacks/boulder_rubble_62x62.png"
target_path = "sprites/attacks/boulder_attack_hit_0.png"

# Cinematics
[[images]]
path = "cinematics/intro/acrab_travelling.png"
[[images]]
path = "cinematics/intro/asteroid_waves.png"
[[images]]
path = "cinematics/intro/clear.png"
[[images]]
path = "cinematics/intro/falling_scene_animated.png"
[[images]]
path = "cinematics/intro/planet.png"
[[images]]
path = "cinematics/intro/falling_ship.png"
[[images]]
path = "cinematics/intro/screaming_scene.png"
[[images]]
path = "cinematics/intro/transform.png"
