[[images]]
name = "enemy"
path = "sprites/ball_red_large.png"
invert_colors = true
width = 12

[[images]]
name = "star"
path = "sprites/star.png"
width = 8

[[images]]
name = "score-icon"
target_path = "sprites/score-icon.png"
invert_colors = true
path = "sprites/star.png"
width = 10


[[images]]
name = "enemy-icon"
target_path = "sprites/enemy-count-icon.png"
invert_colors = true
path = "sprites/ball_red_large.png"
width = 10

[[images]]
path = "sprites/melee_slash.png"

[[images]]
path = "sprites/bullet_particles.png"

[[images]]
path = "sprites/crosshairs/squiggly.png"

[[images]]
path = "sprites/crosshairs/gun_sight.png"

[[images]]
path = "sprites/crosshairs/gun_sight.png"
target_path = "sprites/crosshairs/gun_sight_inverted.png"
invert_colors = true

[[images]]
path = "backgrounds/stage_asteroid/cavern.png"

[[images]]
path = "backgrounds/stage_asteroid/space.png"

[[images]]
path = "typeface/typeface.png"

[[images]]
name = "pixeboy"
path = "typeface/pixeboy.png"

[[images]]
path = "typeface/pixeboy.png"
target_path = "typeface/pixeboy-inverted.png"
invert_colors = true

[[images]]
path = "typeface/animated_typeface.png"
