[[images]]
name = "player"
path = "sprites/ball_blue_large.png"
width = 12

[[images]]
name = "enemy"
path = "sprites/ball_red_large.png"
invert_colors = true
width = 12

[[images]]
name = "star"
path = "sprites/star.png"
width = 8

[[images]]
path = "typeface/typeface.png"
