[[images]]
name = "enemy"
path = "sprites/ball_red_large.png"
invert_colors = true
width = 12

[[images]]
name = "star"
path = "sprites/star.png"
width = 8

[[images]]
name = "score-icon"
target_path = "sprites/score-icon.png"
invert_colors = true
path = "sprites/star.png"
width = 10


[[images]]
name = "enemy-icon"
target_path = "sprites/enemy-count-icon.png"
invert_colors = true
path = "sprites/ball_red_large.png"
width = 10

[[images]]
path = "sprites/melee_slash.png"

[[images]]
path = "sprites/bullet_particles.png"

[[images]]
path = "sprites/crosshairs/squiggly.png"

[[images]]
path = "sprites/crosshairs/gun_sight.png"

[[images]]
path = "sprites/crosshairs/gun_sight.png"
target_path = "sprites/crosshairs/gun_sight_inverted.png"
invert_colors = true

[[images]]
path = "backgrounds/asteroid/background.png"

[[images]]
path = "backgrounds/asteroid/skybox.png"

[[images]]
path = "backgrounds/rugpark/background.png"

[[images]]
path = "backgrounds/rugpark/skybox.png"

# [[images]]
# path = "backgrounds/main_menu/blank.png"

[[images]]
path = "typeface/typeface.png"

[[images]]
name = "pixeboy"
path = "typeface/pixeboy.png"

[[images]]
path = "typeface/pixeboy.png"
target_path = "typeface/pixeboy-inverted.png"
invert_colors = true

[[images]]
path = "typeface/animated_typeface.png"

# Enemies
[[images]]
path = "sprites/enemies/mosquito_death_1.png"
[[images]]
path = "sprites/enemies/mosquito_death_2.png"
[[images]]
path = "sprites/enemies/mosquito_death_3.png"
[[images]]
path = "sprites/enemies/mosquito_idle_1.png"
[[images]]
path = "sprites/enemies/mosquito_idle_2.png"
[[images]]
path = "sprites/enemies/mosquito_idle_3.png"
[[images]]
path = "sprites/enemies/mosquito_melee_1.png"
[[images]]
path = "sprites/enemies/mosquito_melee_2.png"
[[images]]
path = "sprites/enemies/mosquito_melee_3.png"
[[images]]
path = "sprites/enemies/worm.png"

# Objects
[[images]]
path = "sprites/objects/bench_big.png"
[[images]]
path = "sprites/objects/bench_small.png"
[[images]]
path = "sprites/objects/fiber_tree.png"
[[images]]
path = "sprites/objects/lamp_broken.png"
[[images]]
path = "sprites/objects/lamp.png"
[[images]]
path = "sprites/objects/trash_can_1.png"
[[images]]
path = "sprites/objects/trash_can_2.png"
[[images]]
path = "sprites/objects/trash_can_broken_1.png"
[[images]]
path = "sprites/objects/trash_can_broken_1.png"
[[images]]
path = "sprites/objects/rugpark_sign.png"

# Pickups
[[images]]
path = "sprites/pickups/ammo_9x8.png"
target_path = "sprites/pickups/ammo_1.png"
[[images]]
path = "sprites/pickups/ammo_13x12.png"
target_path = "sprites/pickups/ammo_2.png"
[[images]]
path = "sprites/pickups/bomb_9x9.png"
target_path = "sprites/pickups/bomb1.png"
[[images]]
path = "sprites/pickups/bomb_13x11.png"
target_path = "sprites/pickups/bomb_2.png"
[[images]]
path = "sprites/pickups/health_9x7.png"
target_path = "sprites/pickups/health_1.png"
[[images]]
path = "sprites/pickups/health_14x10.png"
target_path = "sprites/pickups/health_2.png"

# Attacks
[[images]]
path = "sprites/attacks/bloodball_45x45_4.png"
target_path = "sprites/attacks/blood_attack_hovering_1.png"
width = 6
[[images]]
path = "sprites/attacks/bloodball_45x45_4.png"
target_path = "sprites/attacks/blood_attack_hovering_2.png"
width = 10
[[images]]
path = "sprites/attacks/bloodball_45x45_4.png"
target_path = "sprites/attacks/blood_attack_hovering_3.png"
width = 15
[[images]]
path = "sprites/attacks/bloodball_45x45_4.png"
target_path = "sprites/attacks/blood_attack_hovering_4.png"
width = 21
[[images]]
path = "sprites/attacks/bloodball_45x45_4.png"
target_path = "sprites/attacks/blood_attack_hovering_5.png"
width = 28
[[images]]
path = "sprites/attacks/bloodball_45x45_4.png"
target_path = "sprites/attacks/blood_attack_hovering_6.png"
width = 36
[[images]]
path = "sprites/attacks/bloodsplat.png"
target_path = "sprites/attacks/blood_attack_splat_7.png"
